import os

SENDKEY = os.getenv("SENDKEY", "")

# 推送数量
PRE_ZT_MAX_MORNING = 3
PRE_ZT_MAX_AFTERNOON = 3
PRE_ZT_MIN_SCORE = 85

# 涨幅区间
PRE_ZT_MIN_CHG = 0.04
PRE_ZT_MAX_CHG = 0.09

# 量能
PRE_ZT_MIN_VOL_RATIO = 4.0
PRE_ZT_MIN_AUCTION_AMOUNT = 40_000_000
MIN_TURNOVER = 4.0

# 市值
MIN_MKT_CAP = 2e9
MAX_MKT_CAP = 6e10

# 开盘强度
PRE_ZT_OPEN_CHG_MIN = 0.01
PRE_ZT_OPEN_CHG_MAX = 0.08

# 形态
PRE_ZT_PRICE_NEAR_HIGH = 0.98
PRE_ZT_GAP_MIN = 0.01

# 风控（免费动态止损）
STOP_LOSS_ATR_MULTIPLIER = 1.5
MAX_STOP_LOSS_PCT = 0.06
MIN_STOP_LOSS_PCT = 0.02

# 网络
TIMEOUT = 5
